### ISSUE TITLE
May we have higher quality smaller icons plus an accessible WCAG 2.0 AA accessible background 

### ISSUE THREAD

**Issue by sbha5516** [browser-update/browser-update#258]
I find the smaller icons pixelated. Also the background color is not WCAG 2.0 AA acessible. Plus, it will be nice to have fully transparent png image .

**Comment by sbha5516** [comment]
Hi there

I have added the solution required at https://github.com/browser-update/browser-update/pull/259

Please feel free to review and add the change the repo.

Thanks in advance

Sincerely
Swagato Bhatta
Web: swagatobhatta.com

**Comment by adamjohnson** [comment]
+1 to fix the background. Here's what it looks like right now:

![buorg-background-issue](https://cloud.githubusercontent.com/assets/575865/9182985/91a771fa-3f7a-11e5-8eb3-c16f720a3b4e.png)

The blue background color makes things very low contrast. Also, the path to [the image](http://browser-update.org/img/small/f.png) is busted. It looks like #259 incorrectly changes the extension to `.png` instead of `.gif`. #259 also changes the background color to a blue for some reason. The correct background color is `#FDF2AB`.

**Comment by josselex** [comment]
it is now included. And the background is fixed.

**Comment by adamjohnson** [comment]
:ok_hand: :+1:
