### ISSUE TITLE
IE11 Enterprise Mode is treated as outdated

### ISSUE THREAD

**Issue by odieman44** [browser-update/browser-update#291]
When running IE11 under Enterprise Mode, the browser is detected as IE8 and is marked as outdated.  Can this be fixed?  Our enterprise is required to support the use of this feature in IE11 and would like to use browser-update as well.

To enter Enterprise Mode, open IE11.  Click Tools, then select Enterprise Mode.

Per MSDN, the UserAgent string for IE11 Enterprise mode is:
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; Tablet PC 2.0)

https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

Thank you.

**Comment by Paurian** [comment]
Hi,
Enterprise Mode is a new feature in IE 11 that downgrades it's interpreting engine to that if IE 8. This is to allow old business applications that don't handle newer features properly to run in a modern browser.

What that means for you is that a browser in Enterprise Mode essentially is IE 8 in a shinier interface. I think the browser-update code is functioning appropriately for this situation. I suppose the question is why you're using the browser-update library.

Is it to ensure that your website's code runs smoothely and to make code easier to maintain?

Or is it because you want provide a public service announcement about their browser version?

Though from a developer's stand-point, the former question has more validity and importance, I can see someone wanting to do a public service anouncement on their site - though I'm not sure this is the right library for that.

**Comment by odieman44** [comment]
Thank you very much.  After researching IE 11 Enterprise Mode further, I agree with your analysis.  I will close the issue.
