### ISSUE TITLE
Message not showing for IE10

### ISSUE THREAD

**Issue by johnway2** [browser-update/browser-update#292]
I am using Browser Stack to test my website using IE10 on Windows 7.
Allowing the browserupdate.org to decide what browsers to alert the user for, IE10 doesn't get notified, even though the default is IE<=10. If I uncheck the "Notify recommended set of browsers", but I don't make any changes, then IE10 does get the notification.
Should IE10 on Windows 7 be flagged with the default settings?

**Comment by Paurian** [comment]
I experienced similar issues when targetting IE browsers 9 and lower. When the vs is set as follows:
vs: { i: 9, f: 25, o: 12.1, s: 7 }
It turns out that the order of browser user agent checks is off. Because "Trident" is not consistent across MSIE versions (e.g. MSIE 9 has Trident versions 4 and 5 - http://useragentstring.com/pages/Internet%20Explorer/ ) and because, if Trident exists - which it has since IE  - it up-scales the version number such that Trident 5 is translated to IE 10, which it is not. I believe the correct thing to do is to check for the MSIE version *before* checking the Trident version... or perhaps fix the check to look at both MSIE and Trident in the User Agent.

The fix for me was to use a local copy of the update.js file and change the order in getBrowser to look at MSIE as the first else-if, followed by both the Trident checks.

**Comment by josselex** [comment]
> I believe the correct thing to do is to check for the MSIE version before checking the Trident version... or perhaps fix the check to look at both MSIE and Trident in the User Agent instead of just one.
This is a problem since compatibility mode returns old versions IE Versions even if you are using a new version. And we do not want to notify these.
Maybe i have to check for both.

**Comment by josselex** [comment]
> This code does not flag IE10 in Windows 7
> This  code DOES flag IE10 in Windows 7. (The website defaults added as a variable)

Maybe in the script the default was not yet set to IE 10 back then. It Should work now I think.
