### ISSUE TITLE
Import via NPM

### ISSUE THREAD

**Issue by hartey11** [browser-update/browser-update#336]
Hi,

I'm trying to include this as part of my javascript bundle. I've downloaded the package via NPM but how do I import it via webpack into my bundled JS?

**Comment by josselex** [comment]
@ddanier 
Any Idea? What needs to be done for this?

**Comment by ddanier** [comment]
In general it should be possible to import the library, see: https://webpack.js.org/guides/webpack-and-typescript/#using-3rd-party-libraries

I'm not sure whether the library itself needs to be packed in some special way for this to work (see https://webpack.js.org/guides/author-libraries/#author-a-library). If you need any particular changes to our code please file a pull request.

**Comment by hartey11** [comment]
sorry that question was slightly wrong. I've managed to import the it "import browserUpdate from 'browser-update';" but how do I initialise it within this context?

**Comment by hartey11** [comment]
something like this?

import browserUpdate from 'browser-update';
...
browserUpdate.$buoop = {vs:{i:12,f:-4,o:-4,s:9,c:-4},unsecure:true,api:4};

**Comment by Dan503** [comment]
I was going to create a pull request for this that would fix the issue but I got incredibly confused.

This file:
https://github.com/browser-update/browser-update/blob/master/update.js

Is completely different to this file:
`[local-project-folder]/node_modules/browser-update/update.js`

So instead of trying to figure out what weird system you are using to publish to npm I'll just explain the fix here. It's pretty quick and easy.

Just to be clear, these instructions refer to this file:
`[local-project-folder]/node_modules/browser-update/update.js`
**NOT** this file:
https://github.com/browser-update/browser-update/blob/master/update.js

Currently you have this at the bottom of the update.js file:

````js
var $buoop = $buoop||{};
$bu=$buo($buoop);
````

That is what is causing the incompatibility with webpack and browserify.

Instead, replace it with this:

````js
module.exports = $buo;
````

By changing those last 2 lines, webpack and browserify users will then be able to write this in their javascript:

````js
var browserUpdate = require('browser-update');

browserUpdate({ [configuration-options] })
````

Or if they have an es6 compatible build environment, they would do this:

````js
import browserUpdate from 'browser-update';

browserUpdate({ [configuration-options] })
````

On a side note, if you are going to have completely different files for the browser and npm, then can you ensure that the npm version is stored in git? The file that npm loads by default is defined here in the package.json file: `"main": "update.js"`. You could add an `update.npm.js` file for the npm version and update that property to `"main": "update.npm.js"`.

If you have some sort of automated system for generating the npm version then can you please document it?

**Comment by josselex** [comment]
Thanks a lot for the detailed information. I will add a update.npm.js and update the build system to generate it with your suggested changes.

**Comment by josselex** [comment]
First question: Should update.npm.js be minified? Or is this commonly handled by build tools?

**Comment by josselex** [comment]
the npm's update.js should in general be the same as the normal one (except for the module.export you suggested). But I did not update the npm versions because I still have a problem I do not know how to solve:
The normal script loads lazy-loads the javascript to show the notification (update.show.min.js) only if an outdated browser is detected.
How should this be done with the npm version?
*  Should the update.show.min.js be loaded from browser-update.org? 
* Or is it possible to load the local copy of udate.show.min.js?
* Or should I combine all code in one file?

Do you have an idea how to slove this?
Thanks!

**Comment by Dan503** [comment]
## Should `update.npm.js` be minified?

Nah, if a developer is using npm to load the module then they would already have minification built into their build process. So no need to minify the file.

## How should I load  `update.show.js`?

I think just including all the js in the one `update.npm.js` file is the best option. Lazy-loading js in an npm module is very problematic. :/

1. You can't use a relative path designed to point to a local file on the server because files in the `node_modules` folder don't actually go on the server. They are only referenced to in the site source files.
2. You could instruct people to move the file from the `node_modules` folder into their file system like what babel does with it's babel-polyfill code but this is **_super annoying_** for people and it's likely you could lose some users if you force that on people.
3. You could do it CDN style and have the script reference a file that is hosted online somewhere. This will get flagged as a cross-site-scripting vulnerability in many automated security tests though. The cross-site-scripting flag will lead many clients to ask for the code to be removed, especially government clients. Seeing as the whole point of this project is to get it on as many sites as possible in order to get as many people upgrading as possible, this goes against your best interests. Especially since Government users are the most likely to need the message and doing it CDN style will make them the least likely to receive it.

So yeah, just include the whole thing in the `update.npm.js` file. Up to date browsers will need to download a few extra bytes but that's the least damaging of all the options, especially since js gets cached.

**Comment by Dan503** [comment]
Ideally to avoid all the duplication and having to do everything twice when you make updates to the code, I'd recommend setting up an npm build system for the project. The repeated functionality could get their own files then you can use es6 imports to import the functions into 2 files. One file for the browser and one file for npm.

Try taking a look at my [mq-js](https://github.com/Dan503/mq-js) set up as a reference. The index.js file in the root folder is the one that is read by npm. The one that I edit though is the one in the `/src/_scripts/index.js file`. The setup is basically a modified [Yeogurt](https://github.com/larsonjj/generator-yeogurt) setup.

Also if you're confused by the dependencies vs devDependencies lists in npm, I wrote [this article](https://www.linkedin.com/pulse/npm-dependencies-vs-devdependencies-daniel-tonon) which will likely clear things up for you.

**Comment by josselex** [comment]
Thanks for the help so far. I commited a new version. Could you check if I did it correctly?
I added the update.npm.full.js as the main file. This includes all the code necessary to notifiy the users.

I also added update.npm.js which has only the browser checkcing and lazy-loads the notification from the cdn. Just in case people like this. But I don't know how people can invoke this with import.

**Comment by Dan503** [comment]
That's a good work around to let people decide for themselves if they prefer the cdn method or the full file method :)

Yes, it's possible for people to access the alternate file by doing this when they import it:

````
var browserUpdate = require('browser-update/update.npm.js');

browserUpdate({ [configuration-options] })
````

I think you left the critical `module.exports` line off of the `update.npm.full.js` file though. Without that line at the end of the file it won't work properly.

The changes won't be available on npm until you run the `npm publish` command.

**Comment by Dan503** [comment]
I've done a bit of testing and the export appears to be working now :)

I didn't spot the `module.exports` line before since I was expecting to find it at the bottom of the file. It works ok where it is though so no need to change it.

Just publish it to npm now and the issue can be closed :)

**Comment by Dan503** [comment]
To avoid having to delete all those files that you don't want up on npm before publishing, you can use an `.npmignore` file.

It works the exact same way as a `.gitignore` file except it only applies to npm publishing.

You might like to use this to create it: https://www.npmjs.com/package/npmignore

**Comment by josselex** [comment]
Thank you for all your help! I hope it works now. I published it to npm. It seems I don't need the .npmignore right now because no unneeded files are in the package right now, but thank you for the tip.

**Comment by Dan503** [comment]
No problem :)

I mainly helped out because I really wanted to be able to use this in my projects but it didn't fit into my build process. Now it does :)
