### ISSUE TITLE
Edge, Chrome, and Opera version detection is not working properly

### ISSUE THREAD

**Issue by Dan503** [browser-update/browser-update#345]
I did a test using these settings to check if the version detection was working correctly:

````js
{
vs: { i:100, f:100, o:100, s:100, c:100 },
reminder: 0,
}
````

There are no browsers that have reached version 100 yet so they all should display the upgrade message.

These browsers displayed the message as expected:

- Fire fox
- IE 11

These browsers did **_not_** display the message:

- Edge
- Chrome
- Opera

I wasn't able to test Safari as I don't have a mac.

**Comment by josselex** [comment]
You cannot notify the latest version of each browser! This was possible some years ago in the beginning and I got  lots of complaints by users because site administrators misconfigured the script and always kept notifying users although they were using the latest browser.
See #323 
Maybe it could be implemented with a switch to make sure people do it on purpose but then the message would also needed to be changed ("Your browser is not supported, switch to another one") and the update page needs to be changed,
