### ISSUE TITLE
Show notification for ie and edge separately as they have different version

### ISSUE THREAD

**Issue by NaveenRawat0410** [browser-update/browser-update#367]
How to show notifications for ie and edge separately as they have different versions
is beta version is the latest version this plugin consider?

**Comment by josselex** [comment]
Ok. I will implement the option to treat them differently soon.

No. We consider the latest stable version (EdegeHTML 15)

**Comment by dtzar** [comment]
It would be really nice if you could version the Edge browser using the "Version" versus the "EdgeHTML Version" because the "EdgeHTML version" spans a LARGE chunk of time and features.  For instance if I choose `e: 15` then they could be using a browser from October 13, 2016 (Version 39.14942, EdgeHTML version 15.1492) OR one from April 2017 (Version 40.15063, EdgeHTML 15.15063). https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history

**Comment by josselex** [comment]
@dtzar 
The problem is that the "Version" is not shown in the user agent string. We can only detect EdgeHTML but the trailign digits give you more detailed information

**Comment by dtzar** [comment]
Thanks for the quick response and update @josselex.  Would it be possible to then specify the warning based on the trailing digits (i.e. the 15063 in 15.15063)?

**Comment by bobflorian** [comment]
I'd definitely use and love this too.  Our platform supports only IE11 and the latest version 2 versions of Edge, being able to notify on this separately from IE11 would be helpful.

**Comment by josselex** [comment]
This works now, see:
http://browser-update.org/blog/18_notify_outdated_ie_and_edge_separately/

I've been busy with a complete rewrite of the site so it took me some time.

**Comment by NaveenRawat0410** [comment]
Great thanks

**Comment by dtzar** [comment]
Fantastic, thank you!!
