### ISSUE TITLE
IE11 + windows 10 notification does not appear

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [browser-update/browser-update#409]
Hello,

I cannot get IE11 notification appear. I was trying to use both npm and embeded script taken from browser check.org. Tried different variations but without luck. With test:true = it appears.

i have tried:
`var $buoop = {required:{e:-2,f:-3,o:-3,s:-1,c:-3}, mobile:false, api:2018.08 };`

and
```
browserUpdate({
            required: {
                e: -6, f: -6, o: -6, s: -6, c: -6,
                i: -999
            },
            insecure: true,
            mobile: false,
            test: false
        });
```

and 

```
browserUpdate({
            equired:{e:-2,f:-3,o:-3,s:-1,c:-3}, mobile:false, api:2018.08
        });
```

**Comment by vytautas-pranskunas-** [comment]
I had to cleare cookies before trying again. ALl works.

**Comment by nemchik** [comment]
I had to do both `i: -999` and clear cookies to get it to work. That's kind of disapointing because I would like for users of IE to be reminded that their browser is outdated more than just once.

P.S. after seeing the notification I do not interact with it at all, just refresh the page, and it no longer shows. I would understand if the user had opted to ignore and then select "don't show me again" but that is not what's happening. It's behaving as if the user has done those things even with no interaction at all.

Related: https://github.com/browser-update/browser-update/issues/430

**Comment by nemchik** [comment]
Thanks! I'll use that!
