### ISSUE TITLE
update.min.js is not served over https.

### ISSUE THREAD

**Issue by jaworek** [browser-update/browser-update#412]
Currently update.min.js file is not served over https and it seems there is no option to enable it.

**Comment by josselex** [comment]
Can you show an example?
Because it usually is served over https if the main site is severd over
https.
And if you want it to be always served over https you just have to add
https:

 e.src = "https://browser-update.org/update.min.js";

instead of

 e.src = "//browser-update.org/update.min.js";


Am Fr., 31. Aug. 2018 um 15:29 Uhr schrieb Jan Jaworski <
notifications@github.com>:
