### ISSUE TITLE
Ability to not support a browser at all

### ISSUE THREAD

**Issue by YannPl** [browser-update/browser-update#435]
Hi! 
I work on a project that uses input type="date" and Safari doesn't support this at all even the latest version, I would like to notify all user of safari that my application will not work at its best and that they should update their browser for a new one (preferably firefox or chrome)

I haven't found how to disable all support for safari (same for IE, edge is OK but IE 11 is like safari)
Anyone could show me how to do ?

**Comment by josselex** [comment]
This is not possible to do since we do not encourage this behaviour to notify up-to-date browsers.
You want to ask your users to switch browser from a modern and up-to-date browser just because the date field is needed for your programming. 
You should think about a simple workaround for the date field instead. E.g. on Mobile the people cannot even just switch browser.
