### ISSUE TITLE
Browser versions list is outdated

### ISSUE THREAD

**Issue by k-dauda** [browser-update/browser-update#494]
The hardcoded list of browser versions is outdated: https://github.com/browser-update/browser-update/blob/master/scripts/update.npm.full.js#L8

If this list can not be loaded dynamically to fetch the latest values, it would be nice if it was configurable.

**Comment by josselex** [comment]
I will update the list tomorrow.
What would be your idea to load it dynamically? In general the idea is that people also update the script reulary since some noew browsers/changes/fixes need more than just the list but new code.

It would also be possible to make it configurable, but i don't think that a lot of people will do it.

**Comment by josselex** [comment]
Updated the browser versions in 0723245868fcd45b58fba17a0496c0a673a9af0e
