### ISSUE TITLE
All versions of Chrome getting reported as Out of date

### ISSUE THREAD

**Issue by ajh-df** [browser-update/browser-update#564]
All versions of chrome including 108 are being reported as out of date

Even using the c: -10 option it has no affect

Please resolve ASAP

**Comment by josselex** [comment]
The reason is that almost latest version of chrome has security vulnerabilities. So you can fix this with specifying insecure:false.
see 7b9e2e9eea656fd802293c486cc8e86c5f7521ce

Also there was an error with the detection because chrome now removes the minor versions and only shows 108.0.0.0, see 7b9e2e9eea656fd802293c486cc8e86c5f7521ce
This should be fixed now

**Comment by bluesmoon** [comment]
I see it reporting Chrome 116 as insecure.  116 is the latest version of chrome.  I see this on a 3rd party site that I do not have control over.
